// @title           Anki Backend API
// @version         1.0
// @description     REST API for Anki Backend system. This API provides endpoints for managing decks, notes, cards, and study sessions.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.email  support@anki.example.com

// @license.name  MIT
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token. Example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

package main

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	echoSwagger "github.com/swaggo/echo-swagger"

	_ "github.com/felipesantos/anki-backend/docs" // Swagger docs (generated by swag init)
	"github.com/felipesantos/anki-backend/app/api/middlewares"
	"github.com/felipesantos/anki-backend/app/api/routes"
	"github.com/felipesantos/anki-backend/config"
	"github.com/felipesantos/anki-backend/dicontainer"
	domainEvents "github.com/felipesantos/anki-backend/core/domain/events"
	"github.com/felipesantos/anki-backend/core/services/events"
	"github.com/felipesantos/anki-backend/core/services/health"
	metricsService "github.com/felipesantos/anki-backend/core/services/metrics"
	storageService "github.com/felipesantos/anki-backend/core/services/storage"
	tracingService "github.com/felipesantos/anki-backend/core/services/tracing"
	"github.com/felipesantos/anki-backend/core/interfaces/secondary"
	eventHandlers "github.com/felipesantos/anki-backend/infra/events/handlers"
	infraEvents "github.com/felipesantos/anki-backend/infra/events"
	"github.com/felipesantos/anki-backend/infra/jobs/handlers"
	infraJobs "github.com/felipesantos/anki-backend/infra/jobs"
	"github.com/felipesantos/anki-backend/infra/postgres"
	"github.com/felipesantos/anki-backend/infra/redis"
	"github.com/felipesantos/anki-backend/pkg/jwt"
	"github.com/felipesantos/anki-backend/pkg/logger"
	"github.com/felipesantos/anki-backend/pkg/migrate"
)

func main() {
	// 1. Load configuration
	cfg, err := config.Load()
	if err != nil {
		logger.InitLogger("INFO", "development")
		log := logger.GetLogger()
		if validationErr, ok := err.(*config.ValidationError); ok {
			log.Error("Configuration validation failed", "error", validationErr.Error())
			fmt.Fprintf(os.Stderr, "\n❌ Configuration Error: %s\n\n", validationErr.Error())
			os.Exit(1)
		}
		if requiredErr, ok := err.(*config.RequiredEnvError); ok {
			log.Error("Missing required environment variables", "environment", requiredErr.Environment, "variables", requiredErr.Variables, "error", requiredErr.Error())
			fmt.Fprintf(os.Stderr, "\n❌ Missing Required Environment Variables:\n")
			fmt.Fprintf(os.Stderr, "   Environment: %s\n", requiredErr.Environment)
			fmt.Fprintf(os.Stderr, "   Missing variables: %s\n\n", strings.Join(requiredErr.Variables, ", "))
			os.Exit(1)
		}
		log.Error("Failed to load configuration", "error", err)
		fmt.Fprintf(os.Stderr, "\n❌ Failed to load configuration: %v\n\n", err)
		os.Exit(1)
	}

	// 2. Initialize logger
	logger.InitLogger(cfg.Logger.Level, cfg.Logger.Environment)
	log := logger.GetLogger()
	log.Info("Application starting", "environment", cfg.Logger.Environment, "log_level", cfg.Logger.Level)

	// 3. Initialize tracing
	var tracingSvc *tracingService.TracingService
	if cfg.Tracing.Enabled {
		tracingSvc, err = tracingService.NewTracingService(cfg.Tracing)
		if err != nil {
			log.Error("Failed to initialize tracing service", "error", err)
			os.Exit(1)
		}
		log.Info("Tracing system initialized")
	}

	// 4. Initialize database
	db, err := postgres.NewPostgresRepository(cfg.Database, log)
	if err != nil {
		log.Error("Failed to initialize database connection", "error", err)
		os.Exit(1)
	}
	if err := migrate.RunMigrations(cfg.Database, log); err != nil {
		log.Error("Failed to run migrations", "error", err)
		os.Exit(1)
	}

	// 5. Initialize Redis
	rdb, err := redis.NewRedisRepository(cfg.Redis, log)
	if err != nil {
		log.Error("Failed to initialize Redis connection", "error", err)
		os.Exit(1)
	}

	// 6. Initialize JWT
	jwtSvc, err := jwt.NewJWTService(cfg.JWT)
	if err != nil {
		log.Error("Failed to initialize JWT service", "error", err)
		os.Exit(1)
	}

	// 7. Initialize Events System
	var eventService *events.EventService
	var eventBus secondary.IEventBus
	if cfg.Events.Enabled {
		eventBus = infraEvents.NewInMemoryEventBus(cfg.Events.WorkerCount, cfg.Events.QueueSize, log)
		eventService = events.NewEventService(eventBus)
		if err := eventBus.Start(); err != nil {
			log.Error("Failed to start event bus", "error", err)
			os.Exit(1)
		}
		log.Info("Events system initialized")
	} else {
		eventBus = infraEvents.NewInMemoryEventBus(1, 10, log)
		if err := eventBus.Start(); err != nil {
			log.Error("Failed to start minimal event bus", "error", err)
			os.Exit(1)
		}
	}

	// 8. Initialize DI Package
	dicontainer.Init(db.DB, rdb, eventBus, jwtSvc, cfg, log)

	// 9. Initialize other infra services (Metrics, Health, Jobs, Storage)
	healthService := health.NewHealthService(db, rdb)
	
	var metricsSvc *metricsService.MetricsService
	if cfg.Metrics.Enabled {
		metricsSvc = metricsService.NewMetricsService()
		if cfg.Metrics.EnableHTTPMetrics {
			metricsSvc.RegisterHTTPMetrics()
		}
		if cfg.Metrics.EnableSystemMetrics {
			metricsSvc.RegisterSystemMetrics()
			metricsSvc.RegisterDatabaseCollector(db.DB)
			metricsSvc.RegisterRedisCollector(rdb.Client)
		}
		if cfg.Metrics.EnableBusinessMetrics {
			metricsSvc.RegisterBusinessMetrics()
		}
	}

	var workerPool *infraJobs.WorkerPool
	var scheduler *infraJobs.Scheduler
	if cfg.Jobs.Enabled {
		jobQueue := infraJobs.NewRedisQueue(rdb.Client, cfg.Jobs.RedisQueueKey)
		jobRegistry := infraJobs.NewJobRegistry()
		jobRegistry.Register(handlers.NewExampleHandler("example_job"))
		workerPool = infraJobs.NewWorkerPool(cfg.Jobs.WorkerCount, jobQueue, jobRegistry, log, cfg.Jobs.MaxRetries, cfg.Jobs.RetryDelaySeconds)
		scheduler = infraJobs.NewScheduler(jobQueue, log)
		workerPool.Start()
		scheduler.Start()
	}

	storageRepo, _ := storageService.NewStorageRepository(cfg.Storage, log)
	_ = storageService.NewStorageService(storageRepo, log)

	// 10. Setup Echo server
	e := echo.New()
	e.HideBanner = true
	e.HTTPErrorHandler = middlewares.CustomHTTPErrorHandler

	e.Use(middleware.Recover())
	e.Use(middlewares.CORSMiddleware(cfg.CORS))
	e.Use(middlewares.RequestIDMiddleware())
	if cfg.Tracing.Enabled {
		e.Use(middlewares.TracingMiddlewareWithCustomAttributes())
	}
	if cfg.Metrics.Enabled && cfg.Metrics.EnableHTTPMetrics {
		e.Use(middlewares.MetricsMiddleware(metricsSvc))
	}
	e.Use(middlewares.RateLimitingMiddleware(cfg.RateLimit, rdb.Client))

	// 11. Register routes
	e.GET("/swagger/*", echoSwagger.WrapHandler)
	routes.RegisterHealthRoutes(e, healthService)
	if cfg.Metrics.Enabled {
		routes.RegisterMetricsRoutes(e, metricsSvc, cfg.Metrics.Path)
	}
	routes.RegisterAuthRoutes(e, dicontainer.GetAuthService(), jwtSvc, rdb, dicontainer.GetSessionService())
	routes.RegisterStudyRoutes(e, dicontainer.GetDeckService(), dicontainer.GetFilteredDeckService(), dicontainer.GetCardService(), dicontainer.GetReviewService(), jwtSvc, rdb)
	routes.RegisterContentRoutes(e, dicontainer.GetNoteService(), dicontainer.GetNoteTypeService(), jwtSvc, rdb)
	routes.RegisterUserRoutes(e, dicontainer.GetUserService(), dicontainer.GetProfileService(), dicontainer.GetUserPreferencesService(), jwtSvc, rdb)
	routes.RegisterSystemRoutes(e, dicontainer.GetAddOnService(), dicontainer.GetBackupService(), dicontainer.GetMediaService(), dicontainer.GetSyncMetaService(), jwtSvc, rdb)
	routes.RegisterCommunityRoutes(e, dicontainer.GetSharedDeckService(), dicontainer.GetSharedDeckRatingService(), dicontainer.GetDeletionLogService(), dicontainer.GetUndoHistoryService(), jwtSvc, rdb)

	if cfg.Events.Enabled && eventService != nil {
		eventService.Subscribe(domainEvents.UserRegisteredEventType, eventHandlers.NewEmailVerificationHandler(dicontainer.GetEmailService()))
	}

	// 12. Start server
	serverAddr := fmt.Sprintf("%s:%s", cfg.Server.Host, cfg.Server.Port)
	srv := &http.Server{
		Addr:         serverAddr,
		Handler:      e,
		ReadTimeout:  time.Duration(cfg.Server.ReadTimeout) * time.Second,
		WriteTimeout: time.Duration(cfg.Server.WriteTimeout) * time.Second,
		IdleTimeout:  time.Duration(cfg.Server.IdleTimeout) * time.Second,
	}

	stop := make(chan bool, 1)
	go func() {
		log.Info("Starting HTTP server", "address", serverAddr)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Error("HTTP server error", "error", err)
			stop <- true
		}
	}()

	// 13. Graceful shutdown
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, os.Interrupt, syscall.SIGTERM)
	select {
	case <-sigChan:
		log.Info("Shutting down gracefully...")
	case <-stop:
		log.Info("Server stopped unexpectedly")
	}

	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), time.Duration(cfg.Server.ShutdownTimeout)*time.Second)
	defer shutdownCancel()

	if workerPool != nil {
		workerPool.Stop()
	}
	if scheduler != nil {
		scheduler.Stop()
	}
	if eventBus != nil {
		eventBus.Stop()
	}
	srv.Shutdown(shutdownCtx)
	rdb.Close()
	db.Close()
	if tracingSvc != nil {
		tracingSvc.Shutdown(context.Background())
	}

	log.Info("Server stopped")
}
