// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@anki.example.com"
        },
        "license": {
            "name": "MIT",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns the health status of the application and its dependencies (database, cache). The endpoint follows hexagonal architecture: Handler -\u003e Service (IHealthService) -\u003e Repositories (IDatabaseRepository, ICacheRepository)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "All services are healthy",
                        "schema": {
                            "$ref": "#/definitions/response.HealthResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service is degraded or unhealthy",
                        "schema": {
                            "$ref": "#/definitions/response.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.ComponentHealth": {
            "description": "Health status of a single component (database, redis, etc.)",
            "type": "object",
            "properties": {
                "message": {
                    "description": "Status message or error description",
                    "type": "string",
                    "example": "Connection successful"
                },
                "status": {
                    "description": "\"healthy\" or \"unhealthy\"",
                    "type": "string",
                    "example": "healthy"
                }
            }
        },
        "response.HealthResponse": {
            "description": "Health check response containing overall status, timestamp, and component health statuses",
            "type": "object",
            "properties": {
                "components": {
                    "description": "Component health statuses",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/response.ComponentHealth"
                    }
                },
                "status": {
                    "description": "\"healthy\", \"degraded\", or \"unhealthy\"",
                    "type": "string",
                    "example": "healthy"
                },
                "timestamp": {
                    "description": "ISO 8601 timestamp",
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Anki Backend API",
	Description:      "REST API for Anki Backend system. This API provides endpoints for managing decks, notes, cards, and study sessions.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
